### ISSUE TITLE
how does this work

### ISSUE THREAD

**Issue by Atticuss320** [betterclient/LightVSync#1]
How does this decrease input lag while also having no screen tearing? what about the vsync in sodium settings? should I have that disabled or enabled?

**Comment by betterclient** [comment]
Normal VSync makes the game wait so that you get 60fps for example
LightVSync makes the game not render anything so that you get 60fps, and since your not waiting to get 60fps, the game can check your inputs more, thus reducing input lag

**Comment by betterclient** [comment]
sodium vsync should be disabled, mod itself is enough

**Comment by R00tB33rMan** [comment]
> sodium vsync should be disabled, mod itself is enough

Little lost by the phrasing. Would I effectively set VSync to `ON` versus using `Adaptive` to allow LightVSync to function?

**Comment by betterclient** [comment]
mineecraft vsync should be completely disabled
