### ISSUE TITLE
Qilt compatibility 

### ISSUE THREAD

**Issue by xbxct** [betterclient/LightVSync#2]
---- Quilt Loader: Failed to load ----
Date/Time: 2024/09/22 17:58:20.4723 [+0300]
Quilt Loader Version: 0.26.4

-- Error 1 --

LightVSync requires version [0.16.5, ∞) of fabricloader, which is missing!

- <mods>/LightVSync-1.5.jar

-- Plugin State --

Cycle number = 1
Cycle Step = SOLVE

Loaded Plugins (2):
 - 'quilt_loader' (Builtin)
 - 'quilted_fabric_loader' (Builtin)

---- end of report ----
[17:58:20] [main/ERROR]: For more details see the full crash report file: /storage/emulated/0/Pojav/./Qilt 1.20.1/crash-reports/crash-2024-09-22_17.58.20.4077-quilt_loader.txt

**Comment by betterclient** [comment]
Works for me with quilt 0.24.0 
Can you try updating the mod to the new version?

**Comment by betterclient** [comment]
https://modrinth.com/mod/lightvsync/version/1.8
